spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ems1?serverTimezone=America/Chicago&useSSL=false&allowPublicKeyRetrieval=true
    username: xxxx
    password: xxxx
# HIBERNATE  properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
